"""create initial schema

Revision ID: 3237be2160d3
Revises:
Create Date: 2026-08-09 23:33:52.384911

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "3237be2160d3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_invocations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("related_type", sa.String(), nullable=True),
        sa.Column("related_id", sa.UUID(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("is_stub", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("role", sa.Enum("client", "worker", name="user_role"), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "trust_score",
            sa.Numeric(precision=4, scale=1),
            server_default=sa.text("50.0"),
            nullable=False,
        ),
        sa.Column(
            "completed_task_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("location_lat", sa.Float(), nullable=False),
        sa.Column("location_lng", sa.Float(), nullable=False),
        sa.Column("location_address", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reward_amount", sa.Integer(), nullable=False),
        sa.Column(
            "required_worker_count", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "approved_worker_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "screening",
                "rejected",
                "needs_info",
                "open",
                "in_progress",
                "completed",
                "expired",
                "cancelled",
                name="task_status",
            ),
            server_default=sa.text("'screening'"),
            nullable=False,
        ),
        sa.Column("review_score", sa.Integer(), nullable=True),
        sa.Column("review_summary", sa.Text(), nullable=True),
        sa.Column("review_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "required_worker_count BETWEEN 1 AND 10", name="ck_tasks_required_worker_count"
        ),
        sa.CheckConstraint("reward_amount > 0", name="ck_tasks_reward_amount"),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tasks_client",
        "tasks",
        ["client_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_tasks_location", "tasks", ["location_lat", "location_lng"], unique=False)
    op.create_index("idx_tasks_status_deadline", "tasks", ["status", "deadline_at"], unique=False)
    op.create_table(
        "task_assignments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "accepted",
                "submitted",
                "approved",
                "failed",
                "cancelled",
                "expired",
                name="assignment_status",
            ),
            server_default=sa.text("'accepted'"),
            nullable=False,
        ),
        sa.Column("retake_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "worker_id", name="uq_assignment_task_worker"),
    )
    op.create_table(
        "task_reference_images",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("raw_image_url", sa.String(), nullable=False),
        sa.Column("processed_image_url", sa.String(), nullable=True),
        sa.Column("captured_lat", sa.Float(), nullable=False),
        sa.Column("captured_lng", sa.Float(), nullable=False),
        sa.Column("captured_accuracy_m", sa.Float(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("device_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("exif_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ai_validation_status",
            sa.Enum(
                "pending", "processing", "approved", "rejected", "error", name="validation_status"
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("ai_score", sa.Integer(), nullable=True),
        sa.Column("ai_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("location_check", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("masking_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reality_score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt_no BETWEEN 1 AND 3", name="ck_attempt_no"),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["task_assignments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assignment_id", "attempt_no", name="uq_submission_attempt"),
    )
    op.create_index(
        "idx_submissions_task",
        "submissions",
        ["task_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "direction", sa.Enum("charge", "payout", name="payment_direction"), nullable=False
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("stub_pending", "stub_succeeded", "stub_failed", name="payment_status"),
            server_default=sa.text("'stub_pending'"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    op.drop_index("idx_submissions_task", table_name="submissions")
    op.drop_table("submissions")
    op.drop_table("task_reference_images")
    op.drop_table("task_assignments")
    op.drop_index("idx_tasks_status_deadline", table_name="tasks")
    op.drop_index("idx_tasks_location", table_name="tasks")
    op.drop_index("idx_tasks_client", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("users")
    op.drop_table("ai_invocations")
    # ### end Alembic commands ###

    # create_table が自動生成した ENUM 型は drop_table では消えないため、明示的に削除する
    for enum_name in (
        "payment_status",
        "payment_direction",
        "validation_status",
        "assignment_status",
        "task_status",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
